server:
    port: 8080

zuul:
  routes:
    ordrPlan:
      path: /driverTracking/ordrPlan/**
      url: http://localhost:8090/ordrPlan
    driverTrns:
      path: /driverTracking/driverTrns/**
      url: http://localhost:8090/driverTrns  
    driverBalance:
      path: /driverTracking/driverBalance/**
      url: http://localhost:8090/driverBalance 
    oauth:
      path: /oauth/**
      url: http://localhost:8091/oauth
    deliveryStatus:
      path: /deliveryStatus/updateOrdrStatus/**
      url: http://localhost:8092/updateOrdrStatus 
    dispenseStatus:
      path: /dispenseStatus/ordrDispenseStatus/**
      url: http://localhost:8093/ordrDispenseStatus  
 
security:
  oauth2:
    client:
      clientId: ccg-client
      clientSecret: ccg-secret
    resource:
      user-info-uri: http://localhost:8091/users/user
      token-info-uri: http://localhost:8091/oauth/check_token
      preferTokenInfo: true
      filter-order: 3
  basic:
    enabled: false      